apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
#        image: docker.elastic.co/kibana/kibana:5.6.8
#        image: docker.elastic.co/kibana/kibana-oss:5.6.8
#        image: docker.elastic.co/kibana/kibana-oss:6.2.3
        image: kibana:5.6.8
        env:
        - name: CLUSTER_NAME
          value: estest
        - name:  SERVER_NAME
          value: kibana.kube.pse.beescloud.com
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # For nginx-ingress controller < 0.9.0.beta-18
    ingress.kubernetes.io/ssl-redirect: "true"
    # "413 Request Entity Too Large" uploading plugins, increase client_max_body_size
#    ingress.kubernetes.io/proxy-body-size: 50m
#    ingress.kubernetes.io/proxy-request-buffering: "off"
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: kibana-basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required - kibana"
spec:
  # To enable SSL offloading at ingress level, uncomment the following 5 lines
  #tls:
  #- hosts:
  #  - kibana.kube.pse.beescloud.com
  #  # Name of the secret containing the certificate to be used
  #  secretName: cje-example-com-tls
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
    host: kibana.kube.pse.beescloud.com
