---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch17
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch17
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch17
subjects:
- kind: ServiceAccount
  name: elasticsearch17
  namespace: default
